#! /usr/bin/env node

let { writeFileSync } = require('fs')
let { join } = require('path')
let page = require('../src/site/page')

function writeTheWholeEntireWebPage () {
  let start = Date.now()
  // lol
  let theWholeEntireWebPage = page()
  writeFileSync(join(__dirname, '..', 'public', 'index.html'), theWholeEntireWebPage)
  console.log(`Built site in ${Date.now() - start}ms`)
}
writeTheWholeEntireWebPage()

module.exports = writeTheWholeEntireWebPage
