#! /usr/bin/env node

let { writeFileSync } = require('fs')
let { join } = require('path')

let page =    require('../src/site/page')
let content = require('../src/site/content')
let css =     require('../src/site/css')
let scripts = require('../src/site/scripts')

function writeTheWholeEntireWebPage() {
  // lol
  let theWholeEntireWebPage = page({ content, scripts})
  writeFileSync(join(__dirname, '..', 'public', 'index.html'), theWholeEntireWebPage)
  writeFileSync(join(__dirname, '..', 'public', 'styles.css'), css)
  console.log(`Built site!`)
}
writeTheWholeEntireWebPage()

module.exports = writeTheWholeEntireWebPage
